---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "Download Apache Maven"
      get_url: url=http://apache.claz.org/maven/maven-3/3.1.1/binaries/apache-maven--bin.tar.gz dest=/tmp/apache-maven-3.1.1-bin.tar.gz
    
    - name: "Untar Maven "
      shell: chdir=/tmp creates=/opt/apache-maven-3.1.1 tar -zxf apache-maven-3.1.1-bin.tar.gz -C /opt
    
    - name: "Update path for maven use"
      shell: export PATH=/opt/apache-maven-3.1.1/bin:$PATH

    - name: "Make Maven Wrapper"
      shell: mvn wrapper:wrapper

    - name: "Build with Maven"
      shell: "./mvnw -B clean package"
      register: "output"

    - debug: var=output.stdout_lines
