version: 2.1

orbs:
  maven: circleci/maven@1.1.0
  github: circleci/github@1.0.0

jobs:
  build:
    executor: maven/default
    steps:
      - checkout
      - maven/install
      - maven/run:
          name: Build and Package
          command: mvn clean package --file pom.xml

  create_release:
    executor: github/default
    steps:
      - checkout
      - run:
          name: Create GitHub Release
          command: |
            git config --global user.email "circleci@emailcom"
            git config --global user.name "CircleCI"
            CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            if [ -n "$CURRENT_TAG" ]; then
              echo "Creating a new release..."
              NEW_VERSION="$CURRENT_TAG.0.1"
              RELEASE_NAME=$(git show -s --format=%s $CIRCLE_SHA1)
              curl -X POST "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases" \
                -H "Authorization: token $GITHUB_TOKEN" \
                -d '{
                  "tag_name": "'"$NEW_VERSION"'",
                  "name": "'"$RELEASE_NAME"'",
                  "body": "Circle CI relase"'",
                  "draft": false,
                  "prerelease": false
                }'
            else
              echo "No new tags since the latest release. Skipping release creation."
            fi

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: ToolBox
      - create_release:
          filters:
            tags:
              only: /.*/
